### ISSUE TITLE
oozie-mini-cluster fails with "real" workflow. Seems like oozie shared lib misconfigured

### ISSUE THREAD

**Issue by seregasheypak** [sakserv/hadoop-mini-clusters#30]
Hi, it's successor of https://github.com/sakserv/hadoop-mini-clusters/issues/21
PR is here:
https://github.com/sakserv/hadoop-mini-clusters/pull/29

So, here the exception. I suppose it's the root cause of failure. This 
```
017-03-08 17:16:00 INFO  JPAService:520 - JPA configuration: DriverClassName=org.hsqldb.jdbcDriver,Url=jdbc:hsqldb:mem:oozie-db;create=true,Username=sa,Password=***,MaxActive=10,TestOnBorrow=false,TestOnReturn=false,TestWhileIdle=false,
2017-03-08 17:16:00 INFO  CodecFactory:520 - Using gz as output compression codec
2017-03-08 17:16:00 INFO  ActionService:520 - Initialized action types: [hive, map-reduce, :FORK:, :JOIN:, :END:, hive2, ssh, fs, switch, pig, distcp, java, shell, spark, :START:, sqoop, :KILL:, email, sub-workflow]
2017-03-08 17:16:00 ERROR ShareLibService:517 - org.apache.oozie.service.ServiceException: E0104: Could not fully initialize service [org.apache.oozie.service.ShareLibService], Not able to cache sharelib. An Admin needs to install the sharelib with oozie-setup.sh and issue the 'oozie admin' CLI command to update the sharelib
org.apache.oozie.service.ServiceException: E0104: Could not fully initialize service [org.apache.oozie.service.ShareLibService], Not able to cache sharelib. An Admin needs to install the sharelib with oozie-setup.sh and issue the 'oozie admin' CLI command to update the sharelib
	at org.apache.oozie.service.ShareLibService.init(ShareLibService.java:132)
	at org.apache.oozie.service.Services.setServiceInternal(Services.java:386)
	at org.apache.oozie.service.Services.setService(Services.java:372)
	at org.apache.oozie.service.Services.loadServices(Services.java:305)
	at org.apache.oozie.service.Services.init(Services.java:213)
	at org.apache.oozie.local.LocalOozie.start(LocalOozie.java:64)
	at com.github.sakserv.minicluster.impl.OozieLocalServer.start(OozieLocalServer.java:255)
	at com.github.sakserv.minicluster.impl.OozieLocalServerIntegrationTest.setUp(OozieLocalServerIntegrationTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException: Wrong FS: hdfs://localhost:20112/tmp/share_lib, expected: file:///

```

**Comment by sakserv** [comment]
The fix has been committed. Thanks!
