### ISSUE TITLE
java.lang.NoSuchMethodError when trying to use hadoop-mini-clusters-yarn for Spark tests

### ISSUE THREAD

**Issue by Srogozins** [sakserv/hadoop-mini-clusters#42]
I'm working on testing a Spark job, by submitting it to a local Yarn implementation. To do that, spark-yarn is required. However, when I try to run yarnLocalCluster.start() after building with it, I get following error:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.yarn.util.AbstractLivelinessMonitor: method <init>(Ljava/lang/String;)V not found
```

Looks like some kind of conflict in versions of Yarn components. Any workarounds until it's fixed?

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.test.framework</groupId>
    <artifactId>test-sample</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.github.sakserv</groupId>
            <artifactId>hadoop-mini-clusters</artifactId>
            <version>0.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.github.sakserv</groupId>
            <artifactId>hadoop-mini-clusters-common</artifactId>
            <version>0.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.github.sakserv</groupId>
            <artifactId>hadoop-mini-clusters-yarn</artifactId>
            <version>0.1.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-yarn_2.11</artifactId>
            <version>2.2.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```

TestSample.java:
```java
package org.test.framework;

import org.apache.hadoop.conf.Configuration;

import com.github.sakserv.minicluster.impl.YarnLocalCluster;

public class TestSample {
    public static void main(String[] args) throws Exception {
        YarnLocalCluster yarnLocalCluster = new YarnLocalCluster.Builder()
                .setNumNodeManagers(1)
                .setNumLocalDirs(1)
                .setNumLogDirs(1)
                .setResourceManagerAddress("localhost:8032")
                .setResourceManagerHostname("localhost")
                .setResourceManagerSchedulerAddress("localhost:8030")
                .setResourceManagerResourceTrackerAddress("localhost:8031")
                .setResourceManagerWebappAddress("localhost:8042")
                .setUseInJvmContainerExecutor(false)
                .setConfig(new Configuration())
                .build();
        yarnLocalCluster.start();
    }
}
```

Full backtrace:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.yarn.util.AbstractLivelinessMonitor: method <init>(Ljava/lang/String;)V not found
	at org.apache.hadoop.yarn.server.resourcemanager.rmcontainer.ContainerAllocationExpirer.<init>(ContainerAllocationExpirer.java:36)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceInit(ResourceManager.java:437)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.createAndInitActiveServices(ResourceManager.java:1006)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:266)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:304)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$300(MiniYARNCluster.java:99)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:444)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:107)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:272)
	at com.github.sakserv.minicluster.impl.YarnLocalCluster.start(YarnLocalCluster.java:231)
	at org.test.framework.TestSample.main(TestSample.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by sakserv** [comment]
Thanks for reporting this, @Srogozins - it's not an issue I've encountered, so I'll need to do some testing. I would agree that it looks like a dependency conflict. Hopefully I'll have a bit of time this weekend to take a look.

**Comment by sakserv** [comment]
@Srogozins - truly sorry for the delay, free time has been tough to come by lately.

I was able to recreate the issue you reported. The reason this is happening is because spark-yarn_2.11 includes YARN 2.6.5 libs, while HDP uses YARN 2.7.3.

If you do a `mvn dependency:tree` you'll see the following:

```
[INFO] \- org.apache.spark:spark-yarn_2.11:jar:2.2.0:provided
[INFO]    +- org.apache.hadoop:hadoop-yarn-api:jar:2.6.5:compile
[INFO]    |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO]    |  \- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO]    +- org.apache.hadoop:hadoop-yarn-common:jar:2.6.5:compile
[INFO]    |  +- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO]    |  |  \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO]    |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO]    |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:compile
[INFO]    |  +- org.codehaus.jackson:jackson-xc:jar:1.9.13:compile
[INFO]    |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO]    |  +- com.google.inject.extensions:guice-servlet:jar:3.0:compile
[INFO]    |  +- commons-io:commons-io:jar:2.4:compile
[INFO]    |  \- com.google.inject:guice:jar:3.0:compile
[INFO]    |     +- javax.inject:javax.inject:jar:1:compile
[INFO]    |     \- aopalliance:aopalliance:jar:1.0:compile
[INFO]    +- org.apache.hadoop:hadoop-yarn-server-web-proxy:jar:2.6.5:compile
[INFO]    |  +- org.apache.hadoop:hadoop-yarn-server-common:jar:2.6.5:compile
[INFO]    |  +- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO]    |  \- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO]    \- org.apache.hadoop:hadoop-yarn-client:jar:2.6.5:compile
```

Exclude those 2.6.5 libs and it will fix the issue.

```
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-yarn_2.11</artifactId>
            <version>2.2.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-yarn-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-yarn-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-yarn-server-web-proxy</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-yarn-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Closing this for now, but feel free to reopen if you still have issues. Thanks for your interest and reporting this! I'm going to look into your other report now.
