### ISSUE TITLE
Wrong FS Error when trying to run Local Oozie Server together with Mini HDFS Cluster

### ISSUE THREAD

**Issue by Srogozins** [sakserv/hadoop-mini-clusters#43]
I'm working on a setup for testing oozie workflows in IDE. An attempt to start Oozie Local Server that uses Mini HDFS Cluster instance fails with following error:

```
2017-08-16 13:20:06 WARN  SchedulerService:523 - Error executing runnable [], Wrong FS: hdfs://localhost:12345/tmp/oozie_share_lib, expected: file:///
java.lang.IllegalArgumentException: Wrong FS: hdfs://localhost:12345/tmp/oozie_share_lib, expected: file:///
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:665)
	at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:87)
	at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:440)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1547)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1590)
	at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:676)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1547)
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1590)
	at org.apache.oozie.service.ShareLibService.purgeLibs(ShareLibService.java:491)
	at org.apache.oozie.service.ShareLibService.access$000(ShareLibService.java:64)
	at org.apache.oozie.service.ShareLibService$1.run(ShareLibService.java:153)
	at org.apache.oozie.service.SchedulerService$2.run(SchedulerService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

TestSample.java:
```java
package org.test.framework;
import com.google.common.collect.Lists;
import org.apache.hadoop.conf.Configuration;

import com.github.sakserv.minicluster.impl.HdfsLocalCluster;
import com.github.sakserv.minicluster.impl.OozieLocalServer;
import com.github.sakserv.minicluster.oozie.sharelib.Framework;

public class TestSample {
    public static void main(String[] args) throws Exception {
        HdfsLocalCluster hdfsLocalCluster = new HdfsLocalCluster.Builder()
                .setHdfsNamenodePort(12345)
                .setHdfsNamenodeHttpPort(12341)
                .setHdfsTempDir("embedded_hdfs")
                .setHdfsNumDatanodes(1)
                .setHdfsEnablePermissions(false)
                .setHdfsFormat(true)
                .setHdfsEnableRunningUserAsProxyUser(true)
                .setHdfsConfig(new Configuration())
                .build();

        hdfsLocalCluster.start();

        OozieLocalServer oozieLocalServer = new OozieLocalServer.Builder()
                .setOozieTestDir("embedded_oozie")
                .setOozieHomeDir("oozie_home")
                .setOozieUsername(System.getProperty("user.name"))
                .setOozieGroupname("testgroup")
                .setOozieYarnResourceManagerAddress("localhost")
                .setOozieHdfsDefaultFs("hdfs://localhost:12345")
                .setOozieConf(new Configuration())
                .setOozieHdfsShareLibDir("/tmp/oozie_share_lib")
                .setOozieShareLibCreate(Boolean.TRUE)
                .setOozieLocalShareLibCacheDir("share_lib_cache")
                .setOoziePurgeLocalShareLibCache(Boolean.FALSE)
                .setOozieShareLibFrameworks(
                        Lists.newArrayList(Framework.MAPREDUCE_STREAMING, Framework.OOZIE))
                .build();
        oozieLocalServer.start();
    }
}
```

I've followed example instructions in README.MD, just changed the port to match HDFS cluster's. Not sure if related to #30

**Comment by sakserv** [comment]
Hey @Srogozins - This is a known issue. If you take a look at OozieLocalServerIntegrationTest you'll see a working example (the same pattern is used for all of the mini clusters, so take a look at the *IntegrationTest classes for help). 

Add the following before starting the oozieLocalServer and it will fix the issue:

```
OozieShareLibUtil oozieShareLibUtil = new OozieShareLibUtil(
    oozieLocalServer.getOozieHdfsShareLibDir(),
    oozieLocalServer.getOozieShareLibCreate(),
    oozieLocalServer.getOozieLocalShareLibCacheDir(),
    oozieLocalServer.getOoziePurgeLocalShareLibCache(),
    hdfsLocalCluster.getHdfsFileSystemHandle(),
    oozieLocalServer.getOozieShareLibFrameworks());
oozieShareLibUtil.createShareLib();

oozieLocalServer.start();
```

I've updated the readme to include this step. Feel free to reopen this if you still encounter issues. Thanks!
