### ISSUE TITLE
Insert with Spark 2 Sql Context on Hadoop Mini clusters

### ISSUE THREAD

**Issue by dawudr** [sakserv/hadoop-mini-clusters#59]
I'm trying to use Spark SQL Context with Hadoop-mini-clusters, specifically with inserts from Spark SQL context. Could this be made possible? 

I have HIVE, Thrift server and Spark SQL context working and creating tables and select statements work fine. But I wanted to insert test data using Spark sql context like this but I get this exception: java.lang.IncompatibleClassChangeError: Implementing class

String warehouseLocation = "file:${system:user.dir}/" + hiveLocalMetaStore.getHiveWarehouseDir();
spark = SparkSession
        .builder()
        .appName(PersonControlTest.class.getName())
        .config("spark.sql.warehouse.dir", warehouseLocation)
        .config("hive.metastore.uris","thrift://localhost:" + hiveLocalMetaStore.getHiveMetastorePort())
        .config("spark.master", "local[2]")
        .enableHiveSupport()
        .getOrCreate();
spark.sql("INSERT INTO TABLE test VALUES ('firstname', 'lastname')");

[main] INFO org.apache.hive.service.AbstractService - Service:SessionManager is stopped.[main] INFO org.apache.hive.service.AbstractService - Service:SessionManager is stopped.

java.lang.IncompatibleClassChangeError: Implementing class
at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:763) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) at java.net.URLClassLoader.access$100(URLClassLoader.java:73) at java.net.URLClassLoader$1.run(URLClassLoader.java:368) at java.net.URLClassLoader$1.run(URLClassLoader.java:362) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:361) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.sideEffectResult$lzycompute(InsertIntoHiveTable.scala:226) at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.sideEffectResult(InsertIntoHiveTable.scala:142) at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.doExecute(InsertIntoHiveTable.scala:310) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115) at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:136) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:133) at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:114) at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:86) at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:86) at org.apache.spark.sql.Dataset.<init>(Dataset.scala:186) at org.apache.spark.sql.Dataset.<init>(Dataset.scala:167) at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:65) at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:582)

**Comment by dawudr** [comment]
Reply from a HiveRunner contributor 👍 

It looks like some horrendous classpath issue that you're having. Perhaps set an exception breakpoint on java.lang.IncompatibleClassChangeError and run in a debugger to see what it's failing to load? Then check for that in your classpath, its dependencies etc. I see you've raised an issue in the mini-clusters project also. Are the inserts simply to set-up test data, or actually part of the application. If it is the former, you can use HiveRunner to create and populate Hive tables with test data. Can you create/share a very simple test case that reproduces the issue?

I don't really have any great suggestions regarding performance testing clusters. Previously we've done such things manually; running a job multiple times in an isolated cluster and measuring execution time.

**Comment by sakserv** [comment]
Unfortunately, I've been unable to recreate this issue. If this is still an issue, please feel free to reopen with a link a repo where the issue is reproducible. I'd be happy to take a look.
