### ISSUE TITLE
Unable to create table with HDP 3.0 version

### ISSUE THREAD

**Issue by mj4304** [sakserv/hadoop-mini-clusters#73]
Unable to create table with HDP 3.0 version, getting below error
java.lang.noclassDefFoundError:org/apache/hadoop/hive/thrift/hadoopThriftAuthBridge
       at com.github.sakserv.mimicluster.impl.hiveLocalMetaStore
$StartHiveLocalMetaStore.run(hivelocalMetaStore.java:167)
       at java.lang.thread.run(Thread.java:748)
caused by:java.lanf.classNotFoundException:
org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge
       at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
       at java.net.ClassLoader.loadClass(ClassLoader.java:418)
       
Can you please update the mini-cluster .hive dependency jar with the latest one 3.0 . Thank you

**Comment by JinHelin404** [comment]
got same problem, can someone fix this?
